[package]
name = "raytracer"
version = "0.1.0"
authors = ["Jakob Külzer <jakob.kuelzer@gmail.com>"]
edition = "2018"

[dev-dependencies]
assert_approx_eq = "1.1.0"

[dependencies]
float-cmp = "0.4.0"
sdl2 = "0.32"

[[bin]]
name = "projectile"
path = "src/projectile.rs"